### ISSUE TITLE
Gauge Widget : Filter on Opened Merge Request

### ISSUE THREAD

**Issue by gmarchand** [plouc/mozaik-ext-gitlab#1]
item                          | info       | notes
------------------------------|------------|---------------------------------------------------------------------------------------------
**node** version              |    v5.0.0        | *output from `node --version`*
**npm** version               |     3.3.9       | *output from `npm --version`*
**mozaik-ext-gitlab** version |      ^0.1.0      | *available in project's `package.json`*
**mozaik** version            |     1.4.4       | *available in project's `package.json`*
**mozaik-demo** version       |            | *version of the demo used, depends on which method you used to setup your Mozaïk dashboard*
**component**                 |            | *name of the extension's component or `client` if it's related to the extension's client*
**browser**                   |      Chrome      | *browser used, applyable if the issue is not related to the client*

## Expected behavior

The GitLab Merge Requests Gauge widget only counts `opened` Merge requests

## Actual behavior

The GitLab Merge Requests Gauge widget counts all Merge Requests

## Solution 
http://docs.gitlab.com/ce/api/merge_requests.html#list-merge-requests
```
GET /projects/:id/merge_requests?state=opened
```

**Comment by plouc** [comment]
@gmarchand fixed and available in `0.1.1`, if you have a look at the [demo](https://mozaik-gitlab.herokuapp.com/), you'll now see a proper count.
