### ISSUE TITLE
Members Widget : Better Contributors

### ISSUE THREAD

**Issue by gmarchand** [plouc/mozaik-ext-gitlab#3]
## Expected behavior
I want to see all people who contribute to project

## Actual behavior
I see people who are directly members of this project but I don't see group members. This widget doesn' represent reality

## Solution

Better to use this API http://docs.gitlab.com/ee/api/repositories.html#contributors

**Comment by plouc** [comment]
@gmarchand, I think this feature need another widget to display contributors instead of project members.

**Comment by plouc** [comment]
Available in `mozaik-ext-gitlab@0.2.1`.
See https://github.com/plouc/mozaik-ext-gitlab#gitlab-project-contributors for usage.

**Comment by plouc** [comment]
@gmarchand unfortunately, the contributors endpoint doesn't return proper gitlab users, just names and emails, so we cannot display avatars.
